session data successfully received

2023-04-06 18:38:18 Incoming message from user 792642064:
Message text:
"next"

2023-04-06 18:38:19 User data received:
{'id': 792642064, 'bdate': '28.4.1980', 'city': {'id': 1, 'title': 'Москва'}, 'interests': 'Я люблю книги, кино, спорт. Ходить в клубы. Играть в футбол. Путешествовать и купаться в море.', 'sex': 2, 'first_name': 'Поискун', 'last_name': 'Находилкин', 'can_access_closed': True, 'is_closed': False}

2023-04-06 18:38:19 Adding user 792642064 to DB (if user's not there)

2023-04-06 18:38:19 Search criteria formed:
{'city': 1, 'sex': 1, 'age_to': 50, 'age_from': 34, 'interests': ['кино', 'клубы', 'книги', 'купаться', 'море', 'путешествовать', 'спорт', 'футбол']}

2023-04-06 18:38:19 Getting relevant accounts from DB for user 792642064

2023-04-06 18:38:19 No relevant accounts found in DB.

2023-04-06 18:38:21 
Total found 884
Receiving all necessary details for adding to DB...

2023-04-06 18:38:21 Requesting API for accounts for user 792642064

0.11 %
0.23 %
0.34 %
0.45 %
0.57 %
0.68 %
0.79 %
0.9 %
1.02 %
1.13 %
1.24 %
1.36 %
1.47 %
2023-04-06 18:38:27 11 accounts are ready to be offered.
Starting to suggest!

1.58 %
1.7 %
2023-04-06 18:38:28 Suggestion sent to user 792642064

1.81 %
1.92 %
2.04 %
2.15 %
2.26 %
2.38 %
2.49 %
2.6 %
2.71 %
2.83 %
2.94 %
3.05 %
3.17 %
3.28 %
3.39 %
3.51 %Exception ignored in: <module 'threading' from '/usr/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1567, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
